apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.instance.prefix }}-{{ .Release.Name }}-master
spec:
  selector:
    matchLabels:
      app: {{ .Values.instance.prefix }}-{{ .Release.Name }}-master
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.instance.prefix }}-{{ .Release.Name }}-master
    spec:
      terminationGracePeriodSeconds: 180

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:

      - name: master
        image: hub.cerit.io/scipion/scipion-master:{{ .Values.instance.releaseChannel }}
        imagePullPolicy: Always

        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: INSTANCE_NAME
          value: {{ .Release.Name | quote }}
        - name: INSTANCE_PREFIX
          value: {{ .Values.instance.prefix | quote }}
        - name: OD_DATASET_SPACEIDSHORT
          value: {{ .Values.od.dataset.spaceIdShort | quote }}
        - name: OD_PROJECT_SPACEIDSHORT
          value: {{ .Values.od.project.spaceIdShort | quote }}
        - name: ROOT_PASS
          value: "abc"
        - name: USER_PASS
          value: "abc"
        volumeMounts:
        - name: shared
          mountPath: "/mnt/shared"
        - name: vol-dataset-rw
          mountPath: "/mnt/vol-dataset"
        - name: vol-project-rw
          mountPath: "/mnt/vol-project"
        resources:
          limits:
            cpu: {{ .Values.instance.maxcpu }}
            memory: {{ .Values.instance.maxram }}
          requests:
            cpu: {{ .Values.instance.mincpu }}
            memory: {{ .Values.instance.minram }}
# Now there is no need to use GPU.
#            nvidia.com/gpu: 1 # dedicated GPU
#            cerit.io/gpu-mem: 1 # shared GPU

      serviceAccountName: {{ .Values.instance.prefix }}-{{ .Release.Name }}-tool-spawner-sa
      volumes:

      # Onedata
      # ---------------------
      # No direct mount to the Onedata is needed for the master due to stage-in/out process in the controller. Look in the deployment-controller.yaml file.

      # Auto vol provisioning
      # ---------------------

      # Shared volume between Master and Controller
      - name: shared
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-shared-{{ .Release.Namespace }}

      # Master + Controller cloner (master - tmp)
      - name: vol-dataset-rw
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-vol-dataset-{{ .Release.Namespace }}-{{ .Values.od.dataset.spaceIdShort }}

# TODO RO for RW PVC does not work
#      # Master
#      - name: scipion-vol-dataset-ro
#        persistentVolumeClaim:
#          claimName: pvc-scipion-vol-dataset-$SUBST_NAMESPACE
#          readOnly: true

      # Master + Controller restore,autosave,trapsave
      - name: vol-project-rw
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.instance.prefix }}-{{ .Release.Name }}-vol-project-{{ .Release.Namespace }}-{{ .Values.od.project.spaceIdShort }}

